version: '2'
services:
    jhipstersampleapplication4-app:
        image: jhipstersampleapplication4
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstersampleapplication4-mysql:3306/jhipstersampleapplication4?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - JAVA_OPTS=-Djgroups.tcp.address=NON_LOOPBACK -Djava.net.preferIPv4Stack=true
        ports:
            - 8080:8080
    jhipstersampleapplication4-mysql:
        extends:
            file: mysql.yml
            service: jhipstersampleapplication4-mysql
